### ISSUE TITLE
Memory issue with 3x GIF with 500 frames

### ISSUE THREAD

**Issue by rplankenhorn** [mattt/AnimatedGIFImageSerialization#14] opened 2015-02-23 18:23 UTC
I am seeing an out of memory exception when trying to display a 3x GIF with 500 frames.  I think it has something to do with the size of the mutableImages array.

**Comment by kylef** [comment] 2017-09-14 17:44
Seeing the same, but it doesn't look like the problem is with this library but instead UIImageView. When the UIImageView tries to animate a large animated UIImage with ~500 frames it appears to utilise > 500MB of memory before being killed "Terminated due to memory issue".

Did you file a radar that I can dupe?

**Comment by mattt** [comment] 2019-03-28 13:08
This should be fixed by abb190b4dbfbe16517113220cb3426b77291518e. If not, please let me know, and I'd be happy to reopen and investigate further.

**Closed by mattt** 2019-03-28 13:08 UTC
